"""sync models

Revision ID: 4146c6a0fc49
Revises: 
Create Date: 2025-06-28 12:51:22.050941

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4146c6a0fc49'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('activity_logs', sa.Column('table_modified', sa.String(), nullable=True))
    op.add_column('activity_logs', sa.Column('field_modified', sa.String(), nullable=True))
    op.add_column('activity_logs', sa.Column('old_value', sa.Text(), nullable=True))
    op.add_column('activity_logs', sa.Column('new_value', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('activity_logs', 'new_value')
    op.drop_column('activity_logs', 'old_value')
    op.drop_column('activity_logs', 'field_modified')
    op.drop_column('activity_logs', 'table_modified')
    # ### end Alembic commands ###
