"""add missing user columns

Revision ID: 751a5e9ac9ce
Revises: 4146c6a0fc49
Create Date: 2025-06-28 13:23:30.668810

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '751a5e9ac9ce'
down_revision: Union[str, Sequence[str], None] = '4146c6a0fc49'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Add columns as nullable first
    op.add_column('users', sa.Column('first_name', sa.String(), nullable=True))
    op.add_column('users', sa.Column('last_name', sa.String(), nullable=True))
    
    # Update existing records to have a default first_name
    op.execute("UPDATE users SET first_name = 'User' WHERE first_name IS NULL")
    
    # Now make first_name NOT NULL
    op.alter_column('users', 'first_name', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_name')
    op.drop_column('users', 'first_name')
    # ### end Alembic commands ###
